# -*- coding: utf-8 -*-
"""EV-BMS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YxrW2h0immotOLHvvEJrxN6og-Xsdni0
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from google.colab import files
import io
import numpy as np
import time

from sklearn.ensemble import RandomForestRegressor

# Ensure plots show in Colab
# %matplotlib inline

# Step 1: Upload CSV file
uploaded = files.upload()
filename = list(uploaded.keys())[0]

# Step 2: Read the CSV file with encoding fallback
try:
    df = pd.read_csv(io.BytesIO(uploaded[filename]), encoding='utf-8')
except UnicodeDecodeError:
    df = pd.read_csv(io.BytesIO(uploaded[filename]), encoding='ISO-8859-1')

print("First few rows of the dataset:")
print(df.head())


# ✅ KEEP ONLY THESE 10 OUTPUT PARAMETERS (EXACT CSV NAMES)
keep_outputs = [
    'Velocity [km/h]',
    'Elevation [m]',
    'Battery Voltage [V]',
    'Battery Current [A]',
    'Battery Temperature [°C]',
    'Max Battery Temperature [°C]',
    'SOC',
    'Ambient Temperature [°C]',
    'Heat Exchanger Temperature [°C]',
    'Cabin Temperature Sensor [°C]'
]
# Keep only columns that exist in the dataset
keep_outputs = [col for col in keep_outputs if col in df.columns]

# Drop all other columns
df = df[keep_outputs]

print("Columns kept for modeling:")
print(df.columns.tolist())

# Step 3: Identify numeric columns
numeric_columns = [
    col for col in df.select_dtypes(include=['float64', 'int64']).columns
    if col not in exclude_outputs
]

if not numeric_columns:
    print("No numeric columns found. Please upload a valid dataset with numeric data.")
else:
    # Step 4: Identify a time column if available
    possible_time_columns = ['Time', 'Timestamp', 'time', 'timestamp']
    time_column = next((col for col in df.columns if col in possible_time_columns), None)

    # Step 5: Loop over each numeric column as target
    for target_column in numeric_columns:
        print(f"\n========== Analyzing: {target_column} ==========")

        feature_columns = [col for col in numeric_columns if col != target_column]
        if not feature_columns:
            print("Not enough features to predict this column.")
            continue

        overall_start_time = time.time()

        # Drop rows with missing values
        data = df[feature_columns + [target_column]].dropna()

        X = data[feature_columns]
        y = data[target_column]

        # Split data
        X_train, X_test, y_train, y_test = train_test_split(
            X, y, test_size=0.2, random_state=42
        )

        # Model training and prediction timing
        simulation_start_time = time.time()

        # 🔥 UPDATED MODEL (ONLY CHANGE)
        model = RandomForestRegressor(
            n_estimators=300,
            max_depth=20,
            min_samples_split=5,
            min_samples_leaf=2,
            random_state=42,
            n_jobs=-1
        )

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        simulation_end_time = time.time()
        simulation_time = simulation_end_time - simulation_start_time

        # Show Actual vs Predicted (first 10 rows)
        comparison_df = pd.DataFrame({
            'Actual': y_test.values[:10],
            'Predicted': y_pred[:10]
        })
        print(comparison_df)

        # Get time values for plotting
        if time_column and time_column in df.columns:
            time_series = df.loc[y_test.index, time_column].fillna(method='ffill').values[:50]
            x_label = time_column
        else:
            time_series = list(range(50))
            x_label = 'Sample Index'

        # Calculate error metrics
        mse = mean_squared_error(y_test, y_pred)
        mae = mean_absolute_error(y_test, y_pred)
        rmse = np.sqrt(mse)

        # MAPE and Accuracy calculation
        mask = y_test != 0
        if np.any(mask):
            mape = np.mean(np.abs((y_test[mask] - y_pred[mask]) / y_test[mask])) * 100
            accuracy = 100 - mape
        else:
            mape = np.nan
            accuracy = np.nan

        # Plot results
        plt.figure(figsize=(8, 4))
        plt.plot(time_series, y_test.values[:50], label='Actual', marker='o')
        plt.plot(time_series, y_pred[:50], label='Predicted', marker='x')
        plt.title(
            f'{target_column} - Actual vs Predicted\nAccuracy: {accuracy:.2f}%'
            if not np.isnan(accuracy)
            else f'{target_column} - Actual vs Predicted\nAccuracy: N/A'
        )
        plt.xlabel(x_label)
        plt.ylabel(target_column)
        plt.grid(True)
        plt.legend()
        plt.tight_layout()
        plt.show()

        # Print error metrics
        print(f"Mean Squared Error (MSE) for {target_column}: {mse:.4f}")
        print(f"Mean Absolute Error (MAE) for {target_column}: {mae:.4f}")
        print(f"Root Mean Squared Error (RMSE) for {target_column}: {rmse:.4f}")
        if not np.isnan(mape):
            print(f"Mean Absolute Percentage Error (MAPE): {mape:.2f}%")
            print(f"Accuracy: {accuracy:.2f}%")
        else:
            print("MAPE and Accuracy could not be computed due to zero values in actuals.")

        # Execution timing
        overall_end_time = time.time()
        execution_time = overall_end_time - overall_start_time

        print(f"Simulation Time (Model Training + Prediction): {simulation_time:.4f} seconds")
        print(f"Total Execution Time (Data + Plot + Metrics): {execution_time:.4f} seconds")